version: '3.8'

services:

  server:
    image: ghcr.io/silkkycloud/libreddit:0.21.7
    hostname: libreddit
    networks:
      - public
    deploy:
      mode: replicated
      replicas: 6
      placement:
        max_replicas_per_node: 2
        constraints:
          - "node.labels.web_server == true"
      resources:
        limits:
          cpus: '3'
          memory: 4G
        reservations:
          cpus: '1'
          memory: 1G
      labels:
        - "traefik.enable=true"
        # Router
        - "traefik.http.routers.libreddit.rule=Host(`${HOSTNAME}`)"
        - "traefik.http.routers.libreddit.entrypoints=websecure"
        - "traefik.http.routers.libreddit.tls=true"
        - "traefik.http.routers.libreddit.middlewares=libreddit-headers"
        - "traefik.http.routers.libreddit.service=libreddit-service"
        # Middleware
        - "traefik.http.middlewares.libreddit-headers.headers.framedeny=true"
        # Service
        - "traefik.http.services.libreddit-service.loadbalancer.server.port=8080"
        - "traefik.http.services.libreddit-service.loadbalancer.sticky.cookie=true"
        - "traefik.http.services.libreddit-service.loadbalancer.sticky.cookie.secure=true"
        - "traefik.http.services.libreddit-service.loadbalancer.sticky.cookie.samesite=strict"
    environment:
      - LIBREDDIT_DEFAULT_USE_HLS=on
      - LIBREDDIT_DEFAULT_SHOW_NSFW=on
      - LIBREDDIT_DEFAULT_THEME=dark

networks:
  public:
    external: true